import type { Track } from "./types";

export const MOCK_TRACKS: Track[] = [
  { id: "t1", title: "Blinding Lights", artist: "The Weeknd", genre: "pop", bpm: 171, energy: 0.9, durationSec: 200, decade: "2020s" },
  { id: "t2", title: "Titanium (feat. Sia)", artist: "David Guetta", genre: "edm", bpm: 126, energy: 0.86, durationSec: 245, decade: "2010s" },
  { id: "t3", title: "Levitating", artist: "Dua Lipa", genre: "pop", bpm: 103, energy: 0.82, durationSec: 203, decade: "2020s" },
  { id: "t4", title: "Believer", artist: "Imagine Dragons", genre: "rock", bpm: 125, energy: 0.85, durationSec: 204, decade: "2010s" },
  { id: "t5", title: "Industry Baby", artist: "Lil Nas X", genre: "hiphop", bpm: 150, energy: 0.88, durationSec: 212, decade: "2020s", explicit: true },
  { id: "t6", title: "Lose Yourself", artist: "Eminem", genre: "hiphop", bpm: 171, energy: 0.88, durationSec: 326, decade: "2000s", explicit: true },
  { id: "t7", title: "Don't Stop Me Now", artist: "Queen", genre: "rock", bpm: 156, energy: 0.95, durationSec: 210, decade: "1970s" },
  { id: "t8", title: "Hysteria", artist: "Muse", genre: "rock", bpm: 187, energy: 0.92, durationSec: 228, decade: "2000s" },
  { id: "t9", title: "On My Way (Alan Walker)", artist: "Alan Walker", genre: "edm", bpm: 170, energy: 0.83, durationSec: 191, decade: "2010s" },
  { id: "t10", title: "Bad Guy (Remix)", artist: "Billie Eilish", genre: "pop", bpm: 135, energy: 0.78, durationSec: 194, isRemix: true, decade: "2010s" },
  { id: "t11", title: "Enter Sandman", artist: "Metallica", genre: "rock", bpm: 124, energy: 0.89, durationSec: 331, decade: "1990s" },
  { id: "t12", title: "Stronger", artist: "Kanye West", genre: "hiphop", bpm: 104, energy: 0.83, durationSec: 311, decade: "2000s", explicit: true },
  { id: "t13", title: "Where Are Ü Now", artist: "Skrillex & Diplo", genre: "edm", bpm: 140, energy: 0.8, durationSec: 247, decade: "2010s" },
  { id: "t14", title: "We Found Love", artist: "Rihanna", genre: "pop", bpm: 128, energy: 0.9, durationSec: 224, decade: "2010s" },
  { id: "t15", title: "Sandstorm", artist: "Darude", genre: "edm", bpm: 136, energy: 0.95, durationSec: 228, decade: "2000s" },
  { id: "t16", title: "Mr. Brightside", artist: "The Killers", genre: "rock", bpm: 148, energy: 0.91, durationSec: 222, decade: "2000s" },
  { id: "t17", title: "The Trooper", artist: "Iron Maiden", genre: "rock", bpm: 160, energy: 0.94, durationSec: 248, decade: "1980s" },
  { id: "t18", title: "Uptown Funk", artist: "Mark Ronson", genre: "pop", bpm: 115, energy: 0.9, durationSec: 270, decade: "2010s" },
  { id: "t19", title: "Seven Nation Army", artist: "The White Stripes", genre: "rock", bpm: 124, energy: 0.8, durationSec: 231, decade: "2000s" },
  { id: "t20", title: "Rain On Me", artist: "Lady Gaga", genre: "pop", bpm: 123, energy: 0.86, durationSec: 182, decade: "2020s" },
  { id: "t21", title: "Levels", artist: "Avicii", genre: "edm", bpm: 126, energy: 0.93, durationSec: 221, decade: "2010s" },
  { id: "t22", title: "Waka Waka", artist: "Shakira", genre: "latin", bpm: 128, energy: 0.85, durationSec: 201, decade: "2010s" },
  { id: "t23", title: "Thunderstruck", artist: "AC/DC", genre: "rock", bpm: 134, energy: 0.96, durationSec: 292, decade: "1990s" },
  { id: "t24", title: "Can't Hold Us", artist: "Macklemore", genre: "hiphop", bpm: 146, energy: 0.9, durationSec: 270, decade: "2010s" },
  { id: "t25", title: "Hall of Fame", artist: "The Script", genre: "pop", bpm: 85, energy: 0.7, durationSec: 201, decade: "2010s" },
  { id: "t26", title: "Numb", artist: "Linkin Park", genre: "rock", bpm: 110, energy: 0.88, durationSec: 185, decade: "2000s" },
  { id: "t27", title: "Eye of the Tiger", artist: "Survivor", genre: "rock", bpm: 109, energy: 0.86, durationSec: 245, decade: "1980s" },
  { id: "t28", title: "Gasolina", artist: "Daddy Yankee", genre: "latin", bpm: 95, energy: 0.94, durationSec: 193, decade: "2000s" },
  { id: "t29", title: "Calm Down", artist: "Rema", genre: "afrobeats", bpm: 107, energy: 0.73, durationSec: 239, decade: "2020s" },
  { id: "t30", title: "Zombie", artist: "The Cranberries", genre: "rock", bpm: 167, energy: 0.84, durationSec: 306, decade: "1990s" },
  { id: "t31", title: "Let It Go (Metal Cover)", artist: "Frog Leap", genre: "rock", bpm: 140, energy: 0.92, durationSec: 232, isRemix: true, decade: "2010s" },
  { id: "t32", title: "Surface Pressure (Rock Cover)", artist: "Jonathan Young", genre: "rock", bpm: 150, energy: 0.91, durationSec: 208, isRemix: true, decade: "2020s" },
  { id: "t33", title: "Holding Out for a Hero (Remix)", artist: "Bonnie Tyler", genre: "pop", bpm: 150, energy: 0.9, durationSec: 220, isRemix: true, decade: "1980s" },
  { id: "t34", title: "Party Rock Anthem", artist: "LMFAO", genre: "edm", bpm: 130, energy: 0.92, durationSec: 262, decade: "2010s" },
  { id: "t35", title: "Heat Waves", artist: "Glass Animals", genre: "indie", bpm: 80, energy: 0.65, durationSec: 238, decade: "2020s" },
  { id: "t36", title: "Take On Me (Kygo Remix)", artist: "a-ha", genre: "edm", bpm: 114, energy: 0.86, durationSec: 215, isRemix: true, decade: "2010s" },
  { id: "t37", title: "Higher Love (Kygo Remix)", artist: "Whitney Houston", genre: "edm", bpm: 104, energy: 0.88, durationSec: 212, isRemix: true, decade: "2010s" },
  { id: "t38", title: "We Will Rock You", artist: "Queen", genre: "rock", bpm: 81, energy: 0.95, durationSec: 123, decade: "1970s" },
  { id: "t39", title: "Feel So Close", artist: "Calvin Harris", genre: "edm", bpm: 128, energy: 0.9, durationSec: 231, decade: "2010s" },
  { id: "t40", title: "Flowers", artist: "Miley Cyrus", genre: "pop", bpm: 118, energy: 0.82, durationSec: 201, decade: "2020s" }
];

export const ALL_GENRES = ["pop", "edm", "hiphop", "rock", "latin", "indie", "afrobeats"] as const;
